# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-20 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=128, verbose_name='\u4e8c\u7ef4\u7801')),
                ('model', models.CharField(max_length=128, verbose_name='\u578b\u53f7')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('system', models.CharField(max_length=128, verbose_name='\u6240\u5728\u7cfb\u7edf')),
                ('distribution_cabinet', models.CharField(max_length=128, verbose_name='\u914d\u7535\u67dc')),
                ('local_control_panel', models.CharField(max_length=128, verbose_name='\u5c31\u5730\u63a7\u5236\u67dc')),
                ('dcs_cabinet', models.CharField(max_length=128, verbose_name='DCS\u63a7\u5236\u67dc')),
                ('forward_device', models.CharField(blank=True, max_length=256, verbose_name='\u524d\u5411\u8bbe\u5907')),
                ('backward_device', models.CharField(blank=True, max_length=256, verbose_name='\u540e\u5411\u8bbe\u5907')),
                ('legend', models.CharField(blank=True, max_length=128, verbose_name='\u56fe\u4f8b')),
            ],
            options={
                'db_table': 'storm_devices',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=128, verbose_name='\u4e8c\u7ef4\u7801')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
            ],
            options={
                'db_table': 'storm_workshop',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_to_workshop', to='device.Workshop'),
        ),
    ]
