# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.SlugField(max_length=128, verbose_name='\u4e8c\u7ef4\u7801')),
                ('model', models.CharField(max_length=128, verbose_name='\u578b\u53f7')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
            ],
            options={
                'db_table': 'storm_devices',
            },
        ),
    ]
