# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSignalParameterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='\u8bfb\u6570')),
                ('date', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_parameter_of_device', to='device.Device')),
            ],
            options={
                'db_table': 'device_signal_parameter_record',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='index',
            field=models.SlugField(default=0, max_length=128, null=True, verbose_name='\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='code',
            field=models.SlugField(max_length=128, verbose_name='\u7f16\u7801'),
        ),
    ]
